<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-FOGSK9I" failures="2" tests="8" name="com.testNG_file.My_test_Iretry" time="0.046" errors="0" timestamp="2021-12-28T18:36:18 IST" skipped="6">
  <testcase classname="com.testNG_file.My_test_Iretry" name="credentials" time="0.001">
    <skipped/>
  </testcase> <!-- credentials -->
  <system-out/>
  <testcase classname="com.testNG_file.My_test_Iretry" name="credentials1" time="0.002">
    <failure message="expected [Smith@123] but found [Starc@123]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Smith@123] but found [Starc@123]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.testNG_file.My_test_Iretry.credentials1(My_test_Iretry.java:25)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </failure>
  </testcase> <!-- credentials1 -->
  <system-out/>
  <testcase classname="com.testNG_file.My_test_Iretry" name="credentials1" time="0.006">
    <skipped/>
  </testcase> <!-- credentials1 -->
  <system-out/>
  <testcase classname="com.testNG_file.My_test_Iretry" name="credentials" time="0.003">
    <skipped/>
  </testcase> <!-- credentials -->
  <system-out/>
  <testcase classname="com.testNG_file.My_test_Iretry" name="credentials" time="0.012">
    <skipped/>
  </testcase> <!-- credentials -->
  <system-out/>
  <testcase classname="com.testNG_file.My_test_Iretry" name="credentials1" time="0.004">
    <skipped/>
  </testcase> <!-- credentials1 -->
  <system-out/>
  <testcase classname="com.testNG_file.My_test_Iretry" name="credentials1" time="0.012">
    <skipped/>
  </testcase> <!-- credentials1 -->
  <system-out/>
  <testcase classname="com.testNG_file.My_test_Iretry" name="credentials" time="0.006">
    <failure message="expected [smith] but found [Smith]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [smith] but found [Smith]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.testNG_file.My_test_Iretry.credentials(My_test_Iretry.java:15)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </failure>
  </testcase> <!-- credentials -->
  <system-out/>
</testsuite> <!-- com.testNG_file.My_test_Iretry -->
